name: hello-world.yml
on: push
jobs:
  hello-world-job:
    run-on: Ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
